# Generated by Django 4.2 on 2023-04-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blank_test_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_test_2', models.DateTimeField(blank=True)),
                ('total_price_test_2', models.FloatField(blank=True)),
            ],
        ),
    ]
