# Generated by Django 4.2 on 2023-04-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_blank_test_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blank_test_2',
            name='created_test_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
