# Generated by Django 4.2 on 2023-04-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_blank_test_2_total_price_test_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blank_test_2',
        ),
    ]
